// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type MessageSystemAttributeName string

const (
	MessageSystemAttributeName_AWSTraceHeader                   MessageSystemAttributeName = "AWSTraceHeader"
	MessageSystemAttributeName_All                              MessageSystemAttributeName = "All"
	MessageSystemAttributeName_ApproximateFirstReceiveTimestamp MessageSystemAttributeName = "ApproximateFirstReceiveTimestamp"
	MessageSystemAttributeName_ApproximateReceiveCount          MessageSystemAttributeName = "ApproximateReceiveCount"
	MessageSystemAttributeName_DeadLetterQueueSourceArn         MessageSystemAttributeName = "DeadLetterQueueSourceArn"
	MessageSystemAttributeName_MessageDeduplicationId           MessageSystemAttributeName = "MessageDeduplicationId"
	MessageSystemAttributeName_MessageGroupId                   MessageSystemAttributeName = "MessageGroupId"
	MessageSystemAttributeName_SenderId                         MessageSystemAttributeName = "SenderId"
	MessageSystemAttributeName_SentTimestamp                    MessageSystemAttributeName = "SentTimestamp"
	MessageSystemAttributeName_SequenceNumber                   MessageSystemAttributeName = "SequenceNumber"
)

type MessageSystemAttributeNameForSends string

const (
	MessageSystemAttributeNameForSends_AWSTraceHeader MessageSystemAttributeNameForSends = "AWSTraceHeader"
)

type QueueAttributeName string

const (
	QueueAttributeName_All                                   QueueAttributeName = "All"
	QueueAttributeName_ApproximateNumberOfMessages           QueueAttributeName = "ApproximateNumberOfMessages"
	QueueAttributeName_ApproximateNumberOfMessagesDelayed    QueueAttributeName = "ApproximateNumberOfMessagesDelayed"
	QueueAttributeName_ApproximateNumberOfMessagesNotVisible QueueAttributeName = "ApproximateNumberOfMessagesNotVisible"
	QueueAttributeName_ContentBasedDeduplication             QueueAttributeName = "ContentBasedDeduplication"
	QueueAttributeName_CreatedTimestamp                      QueueAttributeName = "CreatedTimestamp"
	QueueAttributeName_DeduplicationScope                    QueueAttributeName = "DeduplicationScope"
	QueueAttributeName_DelaySeconds                          QueueAttributeName = "DelaySeconds"
	QueueAttributeName_FifoQueue                             QueueAttributeName = "FifoQueue"
	QueueAttributeName_FifoThroughputLimit                   QueueAttributeName = "FifoThroughputLimit"
	QueueAttributeName_KmsDataKeyReusePeriodSeconds          QueueAttributeName = "KmsDataKeyReusePeriodSeconds"
	QueueAttributeName_KmsMasterKeyId                        QueueAttributeName = "KmsMasterKeyId"
	QueueAttributeName_LastModifiedTimestamp                 QueueAttributeName = "LastModifiedTimestamp"
	QueueAttributeName_MaximumMessageSize                    QueueAttributeName = "MaximumMessageSize"
	QueueAttributeName_MessageRetentionPeriod                QueueAttributeName = "MessageRetentionPeriod"
	QueueAttributeName_Policy                                QueueAttributeName = "Policy"
	QueueAttributeName_QueueArn                              QueueAttributeName = "QueueArn"
	QueueAttributeName_ReceiveMessageWaitTimeSeconds         QueueAttributeName = "ReceiveMessageWaitTimeSeconds"
	QueueAttributeName_RedriveAllowPolicy                    QueueAttributeName = "RedriveAllowPolicy"
	QueueAttributeName_RedrivePolicy                         QueueAttributeName = "RedrivePolicy"
	QueueAttributeName_SqsManagedSseEnabled                  QueueAttributeName = "SqsManagedSseEnabled"
	QueueAttributeName_VisibilityTimeout                     QueueAttributeName = "VisibilityTimeout"
)
